<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="hari" failures="0" tests="2" name="com.abinbev.carina.demo.CucumberWebSampleTest" time="15.661" errors="1" timestamp="2022-03-14T20:07:08 IST" skipped="0">
  <testcase classname="com.abinbev.carina.demo.CucumberWebSampleTest" name="tearDownClass" time="2.250">
    <error message="Source &#039;C:\AbinBevDemo\Maz-automation\reports\failed.txt&#039; does not exist" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: Source 'C:\AbinBevDemo\Maz-automation\reports\failed.txt' does not exist
at org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:274)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:781)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:747)
at com.qaprosoft.carina.core.foundation.report.ReportContext.saveArtifact(ReportContext.java:414)
at com.abinbev.carina.demo.CucumberWebSampleTest.tearDownClass(CucumberWebSampleTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:344)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- tearDownClass -->
  <system-out/>
  <testcase classname="com.abinbev.carina.demo.CucumberWebSampleTest" name="feature" time="13.411"/>
  <system-out/>
</testsuite> <!-- com.abinbev.carina.demo.CucumberWebSampleTest -->
